### ISSUE TITLE
Add some room for generic options?

### ISSUE THREAD

**Issue by Nyholm** [php-translation/common#23]
Looking at https://github.com/php-translation/symfony-bundle/issues/326

They issue author wants to sync a specific project with loco. That means that we should be able to pass some options to `TransferableStorage`. 

```php
interface TransferableStorage
{
    export(MessageCatalogueInterface $catalogue, array $options = [])
}
```

Is this something we want to support? Is this a good software design?
This is something we should consider before tagging 2.0. 

@hhamon @odolbeau

**Comment by odolbeau** [comment]
It makes sense IMO! :+1: 

Is there any alternative anyway?
If we don't allow passing options when exporting a catalogue, it means our end users will have to make their storage stateful:

```php
$storage->setOptions([]);
$storage->export($catalogue);
```

I definitively prefer your proposal! :)
Of course, we should have the same parameters for the `import` method.

**Comment by Nyholm** [comment]
Yeah, we dont want stateful services. 

Yeah, I agree. We should do the same for `import`
