### ISSUE TITLE
Release v2.0.0

### ISSUE THREAD

**Issue by odolbeau** [php-translation/common#25]
I don't have enough rights on this repo to create a new release.
@Nyholm could you do it please?

Changelog is up to date, it looks like everything is ready to release v2.0.0! :tada:

**Comment by Nyholm** [comment]
Do we want to do a Release candidate first? That gives us some change to make changes if needed.

**Comment by odolbeau** [comment]
I don't think we need it as the scope of this library is quite limited but we can if you want.

**Comment by Nyholm** [comment]
Version 2.0 is released.
