### ISSUE TITLE
`Storage` VS `TransferrableStorage`

### ISSUE THREAD

**Issue by odolbeau** [php-translation/common#30]
We currently have 2 interfaces in this library `Storage` & `TransferrableStorage`.
They are not linked, we can have a class which implements one of them without implementing the other for example.

It looks like we're almost always using both interface for all our implementations in others libraries:
* In loco adapter : https://github.com/php-translation/loco-adapter/blob/master/src/Loco.php#L32
* In PhraseApp adapter : https://github.com/php-translation/phraseapp-adapter/blob/master/src/PhraseApp.php#L19
* In symfony storage: https://github.com/php-translation/symfony-storage/blob/master/src/FileStorage.php#L28

That's why I propose to remove the `TransferrableStorage` & to move the `export` & `import` method directly into the `Storage` interface.

This will obvisouly lead to a new major release.

WDYT @php-translation/deciders?

**Comment by Nyholm** [comment]
Im not sure all adapters (current and future) will always support "export all" or "import all". I believe that was the reason for splitting them up.

**Comment by odolbeau** [comment]
It looks like for now the only adapter which doesn't implements `TransferrableStorage` is the Transifex one: https://github.com/php-translation/transifex-adapter/blob/master/src/Transifex.php
Anyway, the adapter is outdated and even if it's not implemented, it looks like it's supported by Transifex: https://docs.transifex.com/api/translations#downloading-and-uploading-translations

TBH, I don't have any use case of an adapter which doesn't support the export / import of all translations of a given message catalogue.
For example, this kind of storage is not really usable with the bundle: all commands become useless. You can only create / update translations one by one (from the web UI or the symfony profiler for example) but a collaborator can't retrieve them in its own project.
