### ISSUE TITLE
Merge `php-translation/symfony-storage` in `php-translation/common`

### ISSUE THREAD

**Issue by odolbeau** [php-translation/common#31]
In order to reduce the number of repositories in this organization & to simplify the maintenance, I propose to move the code of `php-translation/common` into this library.

This will implies:
* moving the 2 classes & their tests into this repository
* Add `"symfony/framework-bundle": " ^3.4 || ^4.2 || ^5.0"` into `require-dev` for tests.

This implies the release of a new minor release (no major needed here).

WDYT @php-translation/core?

**Comment by bocharsky-bw** [comment]
Both are pretty simple little repos, sounds ok to me. I wonder if @Nyholm has any plans for the "php-translation/common" repo to be as a separate one?
